import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Dev: The Gathering</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <span>Dev: The Gathering</span>
          </h1>

          <p className={styles.description}>Gotta get them all!</p>
          <div className={styles.grid}>
            <div className={styles.card}>
              <Link href="/app/decentralized">
                <a>DECENTRALIZED (CRYPTO)</a>
              </Link>
            </div>
            <div className={styles.card}>
              <Link href="/app/centralized">
                <a>CENTRALIZED</a>
              </Link>
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
